name:                Zugkontrolle-Gtk
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/spamviech/Zugkontrolle-Gtk#readme
license:             BSD3
author:              spamviech
maintainer:          spamviech@web.de
copyright:           2020 spamviech
category:            Web
extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- Zugkontrolle-Base
- aeson >= 1.2 && < 2
- containers >= 0.5 && < 1
- either >= 5.0 && < 6
- gi-cairo-render >= 0.1 && < 0.2
- gi-cairo-connector >= 0.1 && < 0.2
- gi-gdk >= 3.0.22 && < 3.1
- gi-gtk >= 3.0.36 && < 3.1
- gi-gtk-hs >= 0.3.9 && < 0.4
- haskell-gi-base >= 0.24.0 && < 0.25
- haskell-gi-overloading == 0.0
- mtl >= 2.2 && < 3
- stm >= 2.4 && < 3
- template-haskell >= 2.11 && < 3
- text >= 1.2 && < 2

ghc-options:
  - -Wall
  - -Widentities
  - -Wno-unused-do-bind

library:
  source-dirs: src
