[package]
name = "zugkontrolle"
version = "0.1.0"
authors = ["Wolfgang Witt <Wolfgang.Witt@campus.lmu.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-pigpio = "~0.2.0"
bincode = "1.3.2"

[dependencies.serde]
version = "~1.0.124"
features = ["derive"]

[dependencies.gtk]
version = "~0.9.2"
features = ["v3_24"]

[dependencies.gio]
version = "~0.9.1"
features = ["v2_64"]

[dependencies.cairo-rs]
version = "~0.9.1"
features = ["v1_16"]

[dependencies.glib]
version = "0.10.3"
features = ["v2_64"]
