[package]
name = "zugkontrolle"
version = "2.0.0"
authors = ["Wolfgang Witt <Wolfgang.Witt@campus.lmu.de>"]
edition = "2018"
license = "MIT"
publish = false
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.zugkontrolle-derive]
path = "zugkontrolle-derive"

[dependencies]
rstar = "0.8.2"
log = "0.4.14"
simple_logger = "1.11.0"
take_mut = "0.2.2"
version = "3.0.0"
bincode = "1.3.2"
cfg-if = "1.0.0"
# so far (largely) unused, mentioned so I don't forget how they are called
walkdir = "2.3.2"
serde_yaml = "0.8.17"
argh = "0.1.4"
# probably best to only use one (if any)
once = "0.3.4"
once_cell = "1.7.2"

[dependencies.non-empty-vec]
# crates.io version doesn't support serde-feature
# version = "0.1.2"
git = "https://github.com/yihuang/non-empty-vec"
rev = "8fd0cf1aee69ee0601403b2b6389b9281a5b335b"
features = ["serde"]

[dependencies.serde]
version = "1.0.124"
features = ["derive"]

[dependencies.iced]
# ices_aw only works with crates.io-version for now
# git = "https://github.com/hecrj/iced"
# rev = "4b8ba8309f6645cdcb5bd605f8dd88097f8ee5a7"
version = "0.3.0"
features = ["glow","glow_canvas"]

[dependencies.iced_native]
version = "0.4.0"
[dependencies.iced_graphics]
version = "0.2.0"

[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw"
rev = "7a6918a50fa6784ce7d11348b71ea4331d9d6200"
default-features = false
features = ["color_picker", "card", "modal", "tab_bar", "tabs", "glow"]


# can't be used on non-raspi systems
[target.arm-unknown-linux-gnueabihf.dependencies]
# raspi 0/1
rppal = "0.12.0"
rascam = "0.0.2"
[target.armv7-unknown-linux-gnueabihf.dependencies]
# raspi 2/3/4
rppal = "0.12.0"
rascam = "0.0.2"

[build-dependencies]
cfg_aliases = "0.1.0"

[dev-dependencies]
image = "0.23.14"
