[package]
name = "zugkontrolle"
version = "2.0.0"
authors = ["Wolfgang Witt <Wolfgang.Witt@campus.lmu.de>"]
edition = "2018"
license = "MIT"
publish = false
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.zugkontrolle-derive]
path = "zugkontrolle-derive"

[dependencies]
rust-pigpio = "0.2.0"
bincode = "1.3.2"
rstar = "0.8.2"
log = "0.4.14"
simple_logger = "1.11.0"
argh = "0.1.4"

[dependencies.serde]
version = "1.0.124"
features = ["derive"]

[dependencies.iced]
version = "0.3.0"
features = ["canvas"]
