[package]
name = "zugkontrolle"
version = "2.0.0"
authors = ["Wolfgang Witt <Wolfgang.Witt@campus.lmu.de>"]
edition = "2018"
license = "MIT"
publish = false
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.zugkontrolle-derive]
path = "zugkontrolle-derive"

[dependencies]
rstar = "0.8.2"
log = "0.4.14"
simple_logger = "1.11.0"
take_mut = "0.2.2"
# so far unused, mentioned so I don't forget how they are called
walkdir = "2.3.2"
serde_yaml = "0.8.17"
argh = "0.1.4"
bincode = "1.3.2"
# probably best to only use one (if any)
once = "0.3.4"
once_cell = "1.7.2"
# decide which raspi crate to use
# rppal seems to be the most rusty, but requires target-specific cfg-code from me
# I will probably abstract over the interface anyway, so using c-like bindings might be more convenient
rust-pigpio = "0.2.0"
# requires tokio, so only consider if it is used anyway
# in that case, also enable the corresponding /iced/ feature
#apigpio = "0.1.1"

[dependencies.non-empty-vec]
# version = "0.1.2"
git = "https://github.com/yihuang/non-empty-vec"
rev = "8fd0cf1aee69ee0601403b2b6389b9281a5b335b"
features = ["serde"]

[dependencies.serde]
version = "1.0.124"
features = ["derive"]

[dependencies.iced]
# ices_aw only works with git-version for now
git = "https://github.com/hecrj/iced"
rev = "4b8ba8309f6645cdcb5bd605f8dd88097f8ee5a7"
features = ["glow","glow_canvas"]

[dependencies.iced_aw]
git = "https://github.com/iced-rs/iced_aw"
rev = "cd2edf1dd3f1fff2598bbb01f1e538a22d3865e8"
features = ["color_picker", "card", "modal", "tab_bar", "tabs"]

[target.'cfg(all(unix, target_arch = "armv7"))'.dependencies]
# can't be used on non-raspi systems
rppal = "0.12.0"
