[package]
name = "zugkontrolle"
version = "2.0.0"
authors = ["Wolfgang Witt <Wolfgang.Witt@campus.lmu.de>"]
edition = "2018"
license = "MIT"
publish = false
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# use either gtk3 or gtk4 bindings
# chose exactly 1!
gtk-rs = ["gtk"]
gtk4-rs = ["gtk4"]
default = ["gtk4-rs"]

[dependencies.zugkontrolle-derive]
path = "zugkontrolle-derive"

[dependencies]
rust-pigpio = "0.2.0"
bincode = "1.3.2"
rstar = "0.8.2"
log = "0.4.14"
simple_logger = "1.11.0"
argh = "0.1.4"

[dependencies.serde]
version = "1.0.124"
features = ["derive"]

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk-rs.git"
package = "gtk"
features = ["v3_24_9"]
optional = true

# always use gtk4 once ubuntu gets a package for it
[dependencies.gtk4]
git = "https://github.com/gtk-rs/gtk4-rs.git"
package = "gtk4"
features = ["v4_2"]
optional = true

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs.git"
features = ["v2_66"]

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/gtk-rs.git"
features = ["v1_16"]

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs.git"
features = ["v2_64"]
