name:                 Zugkontrolle
version:              1.1.0.0
github:               "spamviech/Zugkontrolle"
license:              BSD3
author:               "Wolfgang Witt"
maintainer:           "wolfi.witt@gmx.de"
copyright:            "2020 Wolfgang Witt"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:           Steuerung einer Modelleisenbahn über einen Raspberry Pi
# category:           Raspberry Pi

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:          Please see the README on GitHub at <https://github.com/spamviech/Zugkontrolle#readme>

flags:
  gui:
    description: "Erstelle ein graphisches User Interface mit GTK+"
    default: true
    manual: true

when:
  - condition: flag(gui)
    dependencies:
      - gtk3
      - lens
    cpp-options:
      - -DZUGKONTROLLEGUI
  - condition: os(linux)
    dependencies:
      - unix

dependencies:
  - base
  - ghc
  - aeson
  - ansi-terminal
  - bytestring
  - concurrency
  - containers
  - directory
  - hspec
  - mtl
  - optparse-applicative
  - regex-tdfa
  - stm
  - template-haskell
  - text
  - yaml
  - wiringPi

ghc-options:
  - -Wall

library:
  source-dirs: src
  ghc-options:
    - -Wno-name-shadowing
    - -Wno-unused-do-bind

executables:
  Zugkontrolle:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
    dependencies:
      - Zugkontrolle
    when:
      - condition: os(linux)
        extra-libraries:
        - wiringPi

tests:
  Zugkontrolle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
    dependencies:
      - Zugkontrolle
    when:
      - condition: os(linux)
        extra-libraries:
        - wiringPi
