name:                 Zugkontrolle
version:              1.2.0.0
github:               "spamviech/Zugkontrolle"
license:              BSD3
author:               "Wolfgang Witt"
maintainer:           "wolfi.witt@gmx.de"
copyright:            "2020 Wolfgang Witt"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:           Steuerung einer Modelleisenbahn über einen Raspberry Pi
category:           Raspberry Pi

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:          Please see the README on GitHub at <https://github.com/spamviech/Zugkontrolle#readme>

flags:
  gui:
    description: "Erstelle ein graphisches User Interface mit GTK+"
    default: true
    manual: true

when:
  - condition: flag(gui)
    dependencies:
      - gi-gtk-declarative >= 0.6 && < 0.7
      - lens >= 4.16 && < 5
    cpp-options:
      - -DZUGKONTROLLEGUI
  - condition: os(linux)
    dependencies:
      - unix
    when:
      - condition: arch(arm)
        cpp-options:
          - -DZUGKONTROLLERASPI=1

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 1.2 && < 2
  - ansi-terminal >= 0.8 && < 1
  - bytestring >= 0.10 && < 1
  - concurrency >= 1.4 && < 2
  - containers >= 0.5 && < 1
  - directory >= 1.3 && < 2
  - either >= 5.0 && < 6
  - mtl >= 2.2 && < 3
  - optparse-applicative >= 0.14 && < 1
  - stm >= 2.4 && < 3
  - template-haskell >= 2.12 && < 3
  - text >= 1.2 && < 2
  - yaml >= 0.8 && < 1
  - wiringPi >= 1.0 && < 2

ghc-options:
  - -Wall

library:
  source-dirs: src
  ghc-options:
    - -Wno-name-shadowing
    - -Wno-unused-do-bind

executables:
  Zugkontrolle:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
    dependencies:
      - Zugkontrolle
    when:
      - condition: os(linux)
        when:
          - condition: arch(arm)
            extra-libraries:
              - wiringPi
