name:                Zugkontrolle
version:             2.0.0.0
homepage:            https://github.com/spamviech/Zugkontrolle-Cmd#readme
license:             BSD3
author:              Wolfgang Witt
maintainer:          wolfi.witt@gmx.de
copyright:           2020 Wolfgang Witt

# Metadata used when publishing your package
synopsis:           Steuerung einer Modelleisenbahn über einen Raspberry Pi.
category:            Raspberry Pi

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:        Please see the README on GitHub at <https://github.com/spamviech/Zugkontrolle#readme>

extra-source-files:
- README.md
- ChangeLog.md

flags:
    gui:
      description: "Erstelle ein graphisches User Interface mit GTK+."
      default: true
      manual: true
    cmd:
      description: "Starte das Programm mit einem Terminal-Fenster. Deaktivieren verhindert Verwendung des Komandozeilen-UI."
      default: true
      manual: true
 
dependencies:
- base >= 4.7 && < 5
- Zugkontrolle-Base
- directory >= 1.3 && < 2
- text >= 1.2 && < 2
- ansi-terminal >= 0.8 && < 1
- mtl >= 2.2 && < 3

when:
  - condition: flag(gui)
    then:
      dependencies:
      - Zugkontrolle-Gtk
      cpp-options:
      - -DZUGKONTROLLEGUI
      when:
        - condition: flag(cmd)
          then:
              dependencies:
              - Zugkontrolle-Cmd
          else:
              dependencies:
              - silently >= 1.2 && < 1.3
              cpp-options:
              - -DZUGKONTROLLESILENCE
              when:
                - condition: os(windows)
                  ghc-options:
                  - -optl-mwindows
    else:
        dependencies:
        - Zugkontrolle-Cmd

executables:
    Zugkontrolle:
      source-dirs:      app
      main:             Main.hs
      ghc-options:
      - -threaded
      when:
        - condition: os(linux) && arch(arm)
          extra-libraries:
          - wiringPi
