[package]
name = "zugkontrolle-macros"
version = "3.0.0"
authors = ["Wolfgang Witt <Wolfgang.Witt@campus.lmu.de>"]
edition = "2021"
license = "MIT"
publish = false
resolver = "2"
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.36"
proc-macro-crate = "1.1.3"
quote = "1.0.15"

[dependencies.heck]
version = "0.4.0"
features = ["unicode"]
default-features = false

[dependencies.syn]
version = "1.0.86"
features = ["full", "extra-traits"]
default_features = false
