name:                Zugkontrolle-Cmd
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/spamviech/Zugkontrolle-Cmd#readme
license:             BSD3
author:              spamviech
maintainer:          spamviech@web.de
copyright:           2020 spamviech
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - Zugkontrolle-Base
  - ansi-terminal >= 0.8 && < 1
  - containers >= 0.5 && < 1
  - mtl >= 2.2 && < 3
  - text >= 1.2 && < 2

ghc-options:
  - -Wall
  - -Widentities
  - -Wno-unused-do-bind

library:
  source-dirs: src
