name:                Gleisplan
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/spamviech/Zugkontrolle-Gtk#readme
license:             BSD3
author:              spamviech
maintainer:          spamviech@web.de
copyright:           2020 spamviech
category:            Web
extra-source-files:
- README.md

dependencies:
- base >= 4.14 && < 5
- data-r-tree >= 0.6 && < 0.7
- haskell-gi-overloading == 0.0
- gi-cairo-render >= 0.1 && < 0.2
- gi-cairo-connector >= 0.1 && < 0.2
- gi-gdk >= 4.0.2 && < 4.1
- gi-gio >= 2.0.27 && < 2.1
- gi-graphene >= 1.0.2 && < 1.1
- gi-gsk >= 4.0.2 && < 4.1
- gi-gtk >= 4.0.3 && < 4.1
- hashable >= 1.3 && < 1.4
- haskell-gi-base >= 0.24.5 && < 0.25
- mtl >= 2.2 && < 2.3
- stm >= 2.5 && < 2.6
- template-haskell >= 2.16 && < 3
- text >= 1.2 && < 1.3
- transformers >= 0.5.6.2 && < 0.6
- unordered-containers >= 0.2.13 && < 0.3

ghc-options:
- -Wall
- -Widentities
- -Wno-unused-do-bind

library:
    source-dirs: src

executable:
    source-dirs:      app
    main:             Main.hs
    dependencies:
    - Gleisplan
    ghc-options:
    - -threaded
