name:                Zugkontrolle-Base
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/spamviech/Zugkontrolle-Base#readme
license:             BSD3
author:              spamviech
maintainer:          spamviech@web.de
copyright:           2020 spamviech
category:            Web
extra-source-files:
- README.md

flags:
  cmd:
    description: "Wenn diese Flag false ist wird das silently-package für bestimmte Util-Funktionen verwendet."
    default: true
    manual: true

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 1.2 && < 2
  - containers >= 0.5 && < 1
  - directory >= 1.3 && < 2
  - mtl >= 2.2 && < 3
  - optparse-applicative >= 0.14 && < 1
  - stm >= 2.4 && < 3
  - template-haskell >= 2.12 && < 3
  - text >= 1.2 && < 2
  - yaml >= 0.8 && < 1
  - wiringPi >= 1.0 && < 2

when:
  - condition: os(linux)
    dependencies:
      - unix
    when:
      - condition: arch(arm)
        cpp-options:
          - -DZUGKONTROLLERASPI
  - condition: ! flag(cmd)
    dependencies:
      - silently >= 1.2 && < 1.3
    cpp-options:
      - -DZUGKONTROLLESILENCE

ghc-options:
  - -Wall
  - -Widentities
  - -Wno-unused-do-bind

library:
  source-dirs: src
