name: Build for target

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'The target triple'
        default: 'aarch64-unknown-linux-gnu'
        required: true
        type: string
      profile:
        description: 'Cargo profile to use for compilation'
        required: true
        default: 'release'
        type: string
      raspi:
        description: 'Activate the "raspi" feature'
        required: true
        type: boolean
  workflow_call:
    inputs:
      target:
        description: 'The target triple'
        default: 'aarch64-unknown-linux-gnu'
        required: true
        type: string
      profile:
        description: 'Cargo profile to use for compilation'
        required: true
        default: 'release'
        type: string
      raspi:
        description: 'Activate the "raspi" feature'
        required: true
        type: boolean

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}
        submodules: 'true'
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: ${{ inputs.target }}
        override: true
    - name: Setup Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: true
        args: --profile=${{ inputs.profile }} --target=${{ inputs.target }} ${{ inputs.raspi && '--features=raspi' || '' }}
    - name: Upload artifact (non-windows)
      if: ${{ !contains( inputs.target , 'windows') }}
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: target/${{ inputs.target }}/${{ inputs.profile }}/zugkontrolle
    - name: Upload artifact (Windows)
      if: ${{ contains( inputs.target , 'windows') }}
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: target/${{ inputs.target }}/${{ inputs.profile }}/zugkontrolle.exe
