name: Build, test, lint, check

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'The target triple'
        default: 'aarch64-unknown-linux-gnu'
        required: false
        type: string
      raspi:
        description: 'Activate the "raspi" feature'
        required: true
        type: boolean
  workflow_call:
    inputs:
      target:
        description: 'The target triple'
        default: 'aarch64-unknown-linux-gnu'
        required: false
        type: string
      raspi:
        description: 'Activate the "raspi" feature'
        required: true
        type: boolean

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.sha }}
        submodules: 'true'
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable-${{ inputs.target }}
        override: true
    - name: Setup Cache
      uses: Swatinem/rust-cache@v2
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        use-cross: true
        args: --target=${{ inputs.target }} ${{ inputs.raspi && --features="raspi" }}
